theme: jekyll-theme-minimal 
title: "Profil - Portfolio de Paul Peudecoeur"
description: "Actuellement en formation à l'ORT Daniel Mayer de Montreuil (93), je poursuis ma deuxième année de BTS SIO avec une spécialisation en Solutions d'Infrastructure."
header-img: "/pp.png" 
